services:
  api:
    environment:
      API_PORT: 8000
      AZURE_STORAGE: database
    networks:
      - default_network
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"

  frontend:
    environment:
      FRONTEND_PORT: 8001
      API_BASE_URL: http://api:8000
    networks:
      - default_network
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "8001:8001"

networks:
  default_network:
